INSERT INTO eav.object (id, name, object_type_id) VALUES (2, 'Car1', 7);
INSERT INTO eav.object (id, name, object_type_id) VALUES (24, 'car3', 7);
INSERT INTO eav.object (id, name, object_type_id) VALUES (6, 'Car2', 7);
INSERT INTO eav.object (id, name, object_type_id) VALUES (36, 'hdgf x321xx36', 7);
INSERT INTO eav.object (id, name, object_type_id) VALUES (12, 'Driver2', 8);
INSERT INTO eav.object (id, name, object_type_id) VALUES (1, 'Order1', 6);
INSERT INTO eav.object (id, name, object_type_id) VALUES (27, 'driver 3', 8);
INSERT INTO eav.object (id, name, object_type_id) VALUES (229, 'Car13', 7);
INSERT INTO eav.object (id, name, object_type_id) VALUES (37, 'hgfd', 8);
INSERT INTO eav.object (id, name, object_type_id) VALUES (5, 'Driver1', 8);
INSERT INTO eav.object (id, name, object_type_id) VALUES (260, '2018-04-19T19:05:44.499709', 6);
INSERT INTO eav.object (id, name, object_type_id) VALUES (257, 'ParkingVendor1', 10);