INSERT INTO eav.object (id, name, object_type_id) VALUES (2, 'Car1', 7);
INSERT INTO eav.object (id, name, object_type_id) VALUES (24, 'car3', 7);
INSERT INTO eav.object (id, name, object_type_id) VALUES (5, 'Driver1', 8);
INSERT INTO eav.object (id, name, object_type_id) VALUES (6, 'Car2', 7);
INSERT INTO eav.object (id, name, object_type_id) VALUES (12, 'Driver2', 8);
INSERT INTO eav.object (id, name, object_type_id) VALUES (1, 'Order1', 6);
INSERT INTO eav.object (id, name, object_type_id) VALUES (36, 'tdsr', 7);
INSERT INTO eav.object (id, name, object_type_id) VALUES (27, 'driver 3', 8);
INSERT INTO eav.object (id, name, object_type_id) VALUES (37, 'hgfd', 8);
INSERT INTO eav.object (id, name, object_type_id) VALUES (77, 'order 2', 6);
INSERT INTO eav.object (id, name, object_type_id) VALUES (78, 'order 3', 6);
INSERT INTO eav.object (id, name, object_type_id) VALUES (83, 'driver5', 8);
INSERT INTO eav.object (id, name, object_type_id) VALUES (81, 'order 6', 6);
INSERT INTO eav.object (id, name, object_type_id) VALUES (82, 'order 7', 6);
INSERT INTO eav.object (id, name, object_type_id) VALUES (79, 'order4', 6);
INSERT INTO eav.object (id, name, object_type_id) VALUES (85, 'order 8', 6);