INSERT INTO eav.params (id, attr_id, object_id, value) VALUES (11, 1, 1, 'Alex');
INSERT INTO eav.params (id, attr_id, object_id, value) VALUES (12, 2, 1, 'Resh');
INSERT INTO eav.params (id, attr_id, object_id, value) VALUES (13, 3, 1, 'Voronezh');
INSERT INTO eav.params (id, attr_id, object_id, value) VALUES (14, 4, 1, '+71112223344');
INSERT INTO eav.params (id, attr_id, object_id, value) VALUES (15, 5, 1, 'BMW');
INSERT INTO eav.params (id, attr_id, object_id, value) VALUES (16, 6, 1, 'Black');
INSERT INTO eav.params (id, attr_id, object_id, value) VALUES (18, 8, 1, '1500');
INSERT INTO eav.params (id, attr_id, object_id, value) VALUES (19, 9, 1, '15-01-2018 10:36:00');
INSERT INTO eav.params (id, attr_id, object_id, value) VALUES (20, 10, 1, NULL);
INSERT INTO eav.params (id, attr_id, object_id, value) VALUES (21, 11, 1, 'Ожидание');
INSERT INTO eav.params (id, attr_id, object_id, value) VALUES (17, 7, 1, 'B123PH36');
INSERT INTO eav.params (id, attr_id, object_id, value) VALUES (22, 12, 2, 'A000AA36');
INSERT INTO eav.params (id, attr_id, object_id, value) VALUES (23, 13, 2, 'MAN');
INSERT INTO eav.params (id, attr_id, object_id, value) VALUES (24, 14, 2, 'Red');
INSERT INTO eav.params (id, attr_id, object_id, value) VALUES (25, 15, 2, 'Тягач');